server:
  port: 30881
  
spring:
  dubbo:
    application:
      name: divide-service
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 20881
    scan: io.springboard.calculate
