server:
  port: 30883
  
spring:
  dubbo:
    application:
      name: subtract-service
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 20883
    scan: io.springboard.calculate
